### ISSUE TITLE
Rename file Dark-Telegram.styl to Dark-Telegram.user.styl

### ISSUE THREAD

**Issue by biazzotto** [Barina/Dark-Telegram#1]
Dark-Telegram.styl should be renamed to Dark-Telegram.user.styl, so Stylus could recognize and be able to install it.

**Comment by Barina** [comment]
You're right changing now!
Thanks
I never used the styl file to install..

**Comment by Barina** [comment]
Although I think in this case it's a bit unnecessary but can you confirm the fix before closing the issue? thanks
