### ISSUE TITLE
Some requests regarding emoji and window

### ISSUE THREAD

**Issue by prakharb5** [Barina/Dark-Telegram#14]
The current emoji pack doesnt look exactly good. Can there be support to replace them with the MS Segoe UI emoji? 

Also, can the emoji/stickers panel size be enlarged as they are currently small. 

One more thing. Can the chat UI cover the whole web area instead of a previously defined one? One theme has successfully achieved this exact thing. ( Link -- https://github.com/d-Rickyy-b/webogram-x )

**Comment by Barina** [comment]
Hi!

> The current emoji pack doesnt look exactly good. Can there be support to replace them with the MS Segoe UI emoji?

I'll look into changing the emojis 
I saw that the MS one are behind MS licensing I don't really familiar with

> Also, can the emoji/stickers panel size be enlarged as they are currently small.

Yes I'll add an option to set its size!
I think about specific values + small \ medium \ large drop down..

> One more thing. Can the chat UI cover the whole web area instead of a previously defined one? One theme has successfully achieved this exact thing. ( Link -- https://github.com/d-Rickyy-b/webogram-x )

Not quite sure what you meant.. the style in the link is just the vanilla website with different colors
There is an option to enlarge the inside window to the full "web are" in the style settings.
Look for "Enable fullscreen" (although it's kinda buggy now not sure why)

**Comment by prakharb5** [comment]
Wait, settings? How do I access it?

**Comment by Barina** [comment]
I think it depends where you are using it.. but in the browsers you access it through the stylus extension icon and then you click on the cog icon besides the style name
![image](https://user-images.githubusercontent.com/370379/102639711-1e8ba200-4162-11eb-97c3-632323d48e05.png)
![image](https://user-images.githubusercontent.com/370379/102639745-29decd80-4162-11eb-920f-d3f4bd667a71.png)

**Comment by prakharb5** [comment]
Oh! I didnt know that! Thanks! I will surely use them!

Edit --  Thank you! I did not know it had so many customization!

**Comment by Barina** [comment]
No problem glad to help :D
Yes this style is all about customization lol

**Comment by prakharb5** [comment]
![Screenshot 2020-12-18 at 22 33 02](https://user-images.githubusercontent.com/51435948/102640775-01b29700-4181-11eb-9301-2e633ecef129.png)

Um, its a bit cut off.

![Screenshot 2020-12-18 at 22 33 28](https://user-images.githubusercontent.com/51435948/102640816-0e36ef80-4181-11eb-9be7-692d701ab17d.png)

While bottom has some wasted area.

**Comment by Barina** [comment]
Like I said it's a bit buggy 😅
A workaround is to just resize the window.. usually I unmaximize and maximize back and its ok

**Comment by prakharb5** [comment]
the webogram x theme is able to achieve this full screen feature properly, fyi. 

Maybe you can get the same 😁

**Comment by prakharb5** [comment]
Ok, disabling the custom app background seems to fix it.

**Comment by prakharb5** [comment]
![Screenshot 2020-12-18 at 22 44 20](https://user-images.githubusercontent.com/51435948/102641734-92d63d80-4182-11eb-9aca-5d223501da4e.png)

Can we make the app toggles more greyish for off state?

**Comment by Barina** [comment]
> the webogram x theme is able to achieve this full screen feature properly, fyi.
> 
> Maybe you can get the same 😁

Yea because its the vanilla theme with just color changes.. we have a lot of changes one of them causing this issue, need to resolve this 😅


> Ok, disabling the custom app background seems to fix it.

That's maybe the change that makes that issue lol but still need further investigation


> ![Screenshot 2020-12-18 at 22 44 20](https://user-images.githubusercontent.com/51435948/102641734-92d63d80-4182-11eb-9aca-5d223501da4e.png)
> 
> Can we make the app toggles more greyish for off state?

lol not sure what are those.. but if you mean the toggles of stylish extension it may be depending on your browser or the developer of the extensions.. were just their users :)

**Comment by prakharb5** [comment]
No, these are toggles of telegram settings. I was asking if we can make the thumb of toggle to be more grey when off.

**Comment by Barina** [comment]
Oh yea, this is kinda old.. but I can see it can be confusing
I'll check it up next

**Comment by Barina** [comment]
I've pushed a new version with emoji popup scaling and changed the toggles background to gray when they are toggled off.
Can you check?

**Comment by Barina** [comment]
About the MS font (symbols you mentioned) they are behind MS licensing that required to purchase it to use in web pages as stated [here](https://www.fonts.com/content/microsoft-typography):
![image](https://user-images.githubusercontent.com/370379/102656389-7afbbb00-417c-11eb-924b-3df6abca7868.png)

Maybe we'll have better luck finding other emojis to include in this style :)

**Comment by prakharb5** [comment]
Thank you so much!

Didn't know about the licensing stuff 😅. What about the EmojiOne font? It is hosted on GitHub only. You might want to give that a try.

**Comment by Barina** [comment]
> Thank you so much!

My pleasure :D

> Didn't know about the licensing stuff 😅. What about the EmojiOne font? It is hosted on GitHub only. You might want to give that a try.

I've opened up new issue (issue #15 ) where we can discuss more about it and in particular.
So we can close this issue :)

**Comment by prakharb5** [comment]
No problem!
