### ISSUE TITLE
File message has no file name text

### ISSUE THREAD

**Issue by andreasomaini** [Barina/Dark-Telegram#8]
That is pretty self-explanatory: uploading a file to a chat results in an empty bubble

![immagine](https://user-images.githubusercontent.com/49907041/80397530-8d0baf00-88b6-11ea-93b1-21fd7e23464b.png)

**Comment by Barina** [comment]
I can confirm this issue only appears in chromium based browsers.
On FireFox it works fine
![image](https://user-images.githubusercontent.com/370379/80503001-fa344880-8979-11ea-9472-704978e3774a.png)
I think this issue is related to the new SVG icons I've made.

**Comment by Barina** [comment]
Alright it seems like `.im_message_document_info` just needed a `float: unset; `
I tested it on Chrome can you confirm it works for you now?

**Comment by andreasomaini** [comment]
Thanks for your work, the name now is displayed correctly (tested on Ferdi) :)
