### ISSUE TITLE
user.css file missing all the semicolons and other punctuation

### ISSUE THREAD

**Issue by obvionaoe** [Barina/Dark-Telegram#9]
So, I just tried to use the user.css file with Ferdi but I just found out that the new version is missing all punctuation signs, like semicolons... rendering it useless

Any chance you could fix this?

Thanks :smile:

**Comment by Barina** [comment]
I think for Ferdi you need to use darkmode.css rather than user.css or user.styl files.
Can you confirm? :)

**Comment by obvionaoe** [comment]
my bad, I didn't see you had a darkmode.css file! thanks a lot
